TPB_URL="https://thepiratebay.la"
KICKASS_URL="http://kickass.to"
EZTV_URL="http://eztvapi.re/"
NYAA_URL="http://www.nyaa.se/"
YTS_URL="http://yts.to"
RARBG_URL="https://rarbg.com"
CPABSIEN_URL="http://www.cpasbien.pw/recherche/films/"
T411_URL=""